name: CICD workshop
on:  
  release: 
jobs: 
  docker:
    runs-on: ubuntu-latest 
    steps:
      #https://github.com/marketplace/actions/build-and-push-docker-images 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: htoo123/randnum:${{ github.ref_name }} #need to change this to take current tag 

      #https://github.com/marketplace/actions/slack-send
      -
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          channel-id: '#sa54-test-submission'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: ${{ env.Name }}\nMatriculation: ${{ env.M_Num }}\nEmail: ${{ env.MyEmail }}\nRepo: ${{ env.MyRepo }}\nImage name: ${{ env.MyImageName }}\nImage url: ${{ env.MyImage_URL }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          Name: Htoo Eain Si Lwin
          M_Num: A0249489
          MyEmail: E0941682@u.nus.edu
          MyRepo: git@github.com:htoohtoo10597/randnum.git
          MyImageName: htoo123/randnum:${{ github.ref_name }} 
          MyImage_URL: https://hub.docker.com/repository/docker/htoo123/randnum